### ISSUE TITLE
Timers/reminders

### ISSUE THREAD

**Issue by vkurchatkin** [JoeHegarty/ratatoskr#1]
Any plans to add timers and/or reminders?

**Comment by JoeHegarty** [comment]
Yes, absolutely. 
The next features I plan to work on are streams, reminders & timers. 

Before that, I'm planning to do some rework on the structure and perhaps move the core into Typescript and leverage DI etc.

**Comment by JoeHegarty** [comment]
I introduced timers in 0.0.5 just now. See https://github.com/JoeHegarty/ratatoskr/wiki/Actor-API#timers

I expect reminders in the next day or 2, they are a little trickier.

**Comment by JoeHegarty** [comment]
Timers and Reminders are both present in v0.0.6

https://github.com/JoeHegarty/ratatoskr/wiki/Actor-API#timers
